version: "3.8"
services:
  php:
    image: gitlab.dylanwilson.dev:5050/dylan/minersrealm-panel/php:v1.0
    networks:
      - backend
    volumes:
      - "./php/application.php:/var/www/html/protected/config/internal/application.php"
  apache:
    image: gitlab.dylanwilson.dev:5050/dylan/minersrealm-panel/apache:v1.0
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "33935:80"

networks:
  frontend:
  backend:
