version: '3.8'
services:
  php:
    image: gitlab.dylanwilson.dev:5050/dylan/minersrealm-panel/php:v1.1.1
    networks:
      - backend
    ports:
      - 9000:9000
    volumes:
      - www-data:/var/www/html
      - ./php/application.php:/var/www/html/protected/config/internal/application.php

  apache:
    image: gitlab.dylanwilson.dev:5050/dylan/minersrealm-panel/apache:v1.1.1
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - 33935:80
    volumes:
      - www-data:/var/www/html

networks:
  frontend:
  backend:

volumes:
  www-data:
